version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis
    build: deploy
    volumes:
      - ./deploy/redis/:/redis/data
    ports:
      - 6379:6379
    restart: always


